### ISSUE TITLE
Is there any way to do the opposite: motion photo to live photo

### ISSUE THREAD

**Issue by vickychinghk** [mihir-io/MotionPhotoMuxer#14]
would really appriciate if you have any source about this.
I have been searching for a long time but no clue.

**Comment by NightMean** [comment]
Yes, if you want to extract the Google Motion Photos back to 2 separate files. 
https://github.com/cliveontoast/GoMoPho
https://github.com/ViRb3/google-camera-motion-photo-splitter

**Comment by mihir-io** [comment]
@vickychinghk As @NightMean mentioned, there are a few tools on GitHub that can do it. I'm not sure if they'll necessarily work with the output from this tool though.
