### ISSUE TITLE
about photo format

### ISSUE THREAD

**Issue by yao177** [mihir-io/MotionPhotoMuxer#6]
In addition to `JPG`, there are also photos in `HEIC` format. Is there any way to support it? Thanks!

**Comment by mihir-io** [comment]
Unfortunately not currently. Exiv2 as it comes with a normal package manager doesn't support HEIC. It's possible to compile a version that does, but even then I'm still not sure if it can properly write to HEIC, especially after it has been merged with the video file.

Google supports HEIC motion photos on their newer phones, but this uses a different file format than the Microvideo format used by this script, and I haven't had time to explore how that format works.

**Comment by mihir-io** [comment]
That being said, I am looking to re-write this in Golang in the somewhat-near future since that's a little easier to maintain. It might also open up the possibility of building a version of Exiv2 that supports HEIC and statically-linking it to the Go binary so that it's easy-to-use and doesn't have the limitations of the distributed Exiv2. There are potential legal implications there that I need to look into as well, though other tools seem to do it so maybe it's not an issue.

**Comment by yao177** [comment]
thanks very much anyway!

**Comment by NightMean** [comment]
> Google supports HEIC motion photos on their newer phones, but this uses a different file format than the Microvideo format used by this script, and I haven't had time to explore how that format works.

I have been trying to look into this but from what I've seen, the only one who uses HEIC motion photos as of today is Samsung. ([Sample file](https://github.com/g0ddest/sm_motion_photo/blob/442d7ffa2d514cdb138f82dbd5105b5afadd0c57/tests/data/photo.heic)) and their implementation is different. Windows Photos does not recognize the photo as Motion Photo and if I try to view it/upload it to Google Photos, it doesn't work either. It seems like the Motion photo will only become "motion" when it is being uploaded from Samsung Phone. 

While Android fully supports HEIC/HEIF, Google Camera doesn't. This is the latest post that I was able to find about this. 
https://support.google.com/pixelphone/thread/257241161/google-camera-heic-support?hl=en 

The only way we can get HEIC Motion photos currently is to convert the HEIC photo to JPG via e.g. [ImageMagick](https://imagemagick.org/) and then use this project. 
Note, if you use some random site that does HEIC to JPG conversion, it might not incorporate the ICC profile into the file so the colors will look washed out. 
From my experience [PicFlow](https://picflow.com/convert/heic-to-jpg) was fastest, produced best photos and kept the ICC profile.

**Comment by NightMean** [comment]
> In addition to JPG, there are also photos in HEIC format. Is there any way to support it? Thanks!

@yao177 There is now a separate project that can create single HEIC Motion Photo. Currently only for Windows. 

https://github.com/PetrVys/MotionPhoto2/

**Comment by gototheskinny** [comment]
> > In addition to JPG, there are also photos in HEIC format. Is there any way to support it? Thanks!
> 
> 
> 
> @yao177 There is now a separate project that can create single HEIC Motion Photo. Currently only for Windows. 
> 
> 
> 
> https://github.com/PetrVys/MotionPhoto2/

I'll definitely try it! Ty for letting us know!
