### ISSUE TITLE
can you try my GUI fork?

### ISSUE THREAD

**Issue by gototheskinny** [mihir-io/MotionPhotoMuxer#8]
[https://github.com/gototheskinny/MotionPhotoMuxerGUI](https://github.com/gototheskinny/MotionPhotoMuxerGUI). made by ChatGPT 3.5 and guided by me. it's working on my end. If you add this to your repo please credit me and ChatGPT too. Thank you for your script I appreciate it!

**Comment by mihir-io** [comment]
Very cool! I think this is definitely valuable for folks that aren't as comfortable with a CLI, but I probably won't merge this into the main repo, as I think there would be a better way to incorporate the GUI directly into the code without having it run the main project as a subcommand.

**Comment by gototheskinny** [comment]
> Very cool! I think this is definitely valuable for folks that aren't as comfortable with a CLI, but I probably won't merge this into the main repo, as I think there would be a better way to incorporate the GUI directly into the code without having it run the main project as a subcommand.

I tried to make chatgpt do that but unfortunately it didn't work. I don't have gpt4, I think gpt4 could do that. You could add a FYI to the main repo, that would be helpful for the people who doesn't know about cmd or python. Thank you btw.
